Feature/api 5
azizazhalgaspayeva/dbp-learn pull request #13
Opened 2023-04-18 18:01 UTC by azizazhalgaspayeva

add permissions

2023-04-18 22:28 UTC, aleksandr-semenov-dbp requested changes
убрать кэши

2023-05-04 23:46 UTC, aleksandr-semenov-dbp requested changes

2023-05-04 23:46 UTC, aleksandr-semenov-dbp commented on main/views.py
> +        return super(UserViewSet, self).get_permissions()
Нет, это сложно. Нужно сделать соответствующий перемешен класс и добавить его во вью декларативно

2023-05-04 23:46 UTC, aleksandr-semenov-dbp commented on main/views.py
> +        return super(UserViewSet, self).get_permissions()
Тут вон еще и накопипащено неправильно

2023-05-04 23:47 UTC, aleksandr-semenov-dbp requested changes
Еще не нашел DEFAULT_PERMISSION_CLASSES

2023-05-05 06:45 UTC, aziza-zhalgaspayeva-dbp commented on main/views.py
> +        return super(UserViewSet, self).get_permissions()
А разве можно декларативно сделать разные permissions для разных действий во вью? Как в этом случае, где у get, post, patch должно быть IsAuthenticated, а у delete - isAdmin?

2023-05-05 06:46 UTC, aziza-zhalgaspayeva-dbp commented on main/views.py
> +        return super(UserViewSet, self).get_permissions()
При этом используя ModelViewSet, a не отдельный вью для каждого действия?

2023-05-10 09:56 UTC, aleksandr-semenov-dbp requested changes

2023-05-10 09:56 UTC, aleksandr-semenov-dbp commented on main/permissions.py
> +        return False
Немного не так. Условие же довольно простое - если delete и user не staff - запретить.
В остальных случаях надо возвращать True, об этом позаботятся другие пермишены
Если даже сам пермшен называется DeleteStaffOnly не стоит внутри запутывать людей вводя термин edit_methods - он должен быть про delete а не про edit

2023-05-10 10:53 UTC, merged